### ISSUE TITLE
建议安装curl-devel

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/key-manager#11]
CentOS7 
master
当我执行cmake3 ..的时候，出现错误提示：
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

经检查是没有安装curl-devel。
所以建议官方说明文档上把安装这个的步骤也写进去。
centOS7下执行下面命令安装：
yum install curl-devel

**Comment by bylun** [comment]
希望官方把以下操作写入到官方文档中。
centOS7下执行下面命令安装：
yum install curl-devel

**Comment by JimmyShi22** [comment]
done
