### ISSUE TITLE
使用key-manager加密后找不到加密的密钥

### ISSUE THREAD

**Issue by wanxi112233** [FISCO-BCOS/key-manager#36]
fisco版本 2.11.0
build_chain.sh 2.11.0
当我使用工具生成cipherDataKey并配置到节点config.ini，并执行脚本加密了节点私钥后，启动不了节点，并报错如下
Exceed waiting time. Please try again to start node0 
config file path : config.ini
[2024-11-25 13:46:09] Initializing...
[INITIALIZER][SecureInitializer]privateKey doesn't exist!

**Comment by HaoXuan40404** [comment]
看下节点config.ini里面配置的privateKey路径和密钥文件

**Comment by wanxi112233** [comment]
[storage_security]
    enable=true
    key_manager_ip=127.0.0.1
    key_manager_port=8150
    cipher_data_key=04bf9dbf1dada2987db53a5aed7c5ea1

**Comment by HaoXuan40404** [comment]
类似这部分 [security]
    private_key_path=conf/node.pem，看下node.pem里面的内容是否是正确的

**Comment by wanxi112233** [comment]
[root@VM-0-2-centos conf]# ls
ca.crt        group.1.genesis  node.crt  node.key.bak.1732453382
channel_cert  group.1.ini      node.key  node.nodeid
这是我的conf目录下的文件，没有node.pem文件

**Comment by HaoXuan40404** [comment]
看下node.key的内容，观察他的内容是否被正确加密

**Comment by wanxi112233** [comment]
475d686cbf1a826a35666228b3fc160b这是加密后的值，和官网给的一长串密文有明显区别

**Comment by HaoXuan40404** [comment]
这应该是在加密过程中返回出现了问题，你可以再请求key manager加密的脚本是使用-x命令，打印明细，观察是否是加密失败

**Comment by wanxi112233** [comment]
{
  "id": 83,
  "jsonrpc": "2.0",
  "result": {
    "dataKey": "475d686cbf1a826a35666228b3fc160b",
    "error": 0,
    "info": "success"
  }
}
将原本加密的node.key删除后，再次启动加密脚本bash -x encrypt_node_key.sh 127.0.0.1 8150 /root/fisco2/nodes/127.0.0.1/node0/conf/node.key 04bf9dbf1dada2987db53a5aed7c5ea1
返回的看到是加密成功提示脚本确认加密完成，并成功加密目标文件。
[INFO] "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key" encrypted!

**Comment by HaoXuan40404** [comment]
这个密钥长度看起来并不正常，key manager是否收到了该请求？ 请您观察在base64编码的部分是否兼容你的系统。您的操作系统和硬件版本是什么

**Comment by wanxi112233** [comment]
key manager收到了请求，并返回了我输入的密码的Ascii码
[1732517983047][TRACE][Dec]Receive
[ "04bf9dbf1dada2987db53a5aed7c5ea1" ]

[1732517983047][TRACE][Dec]Respond
{
   "dataKey" : "6d696d61",
   "error" : 0,
   "info" : "success"
}


使用系统自带的base64编码系统，测试编码系统没有问题
[root@VM-0-2-centos conf]# echo "test-string" | base64
dGVzdC1zdHJpbmcK
[root@VM-0-2-centos conf]# echo "dGVzdC1zdHJpbmcK" | base64 -d
test-string

操作系统为CentOS 7.7
为云服务器没有硬件版本

**Comment by HaoXuan40404** [comment]
bash -x encrypt_node_key.sh 127.0.0.1 8150执行时 手动执行一下base64 $ORIGIN_FILE |tr -d "\n" 观察结果，这里看上去是他拿到了一个空，对空加密得到了错误结果

**Comment by wanxi112233** [comment]
执行加密前，获取到了值
[root@VM-0-2-centos scripts]# base64 /root/fisco2/nodes/127.0.0.1/node0/conf/node.key | tr -d "\n"
LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0VBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFLQkcwd2F3SUJBUVFnWk1wblZIUTJydDRuKzFVRlBLY0IKai9sSW4vREpjTkgraktQaGl6eWNRcm1oUkFOQ0FBUVQ1ZERzVVFhVHRkaG1la2Q3MEJXVjRXcHJsK0R3cnJxQwo0S1l3c1Z0VkZjbFh0SHZrV3M3WWdKY0MyZVdjQ3ZYNzg3ZWZURnM2
Qzkzbm5SWkl6UitECi0tLS0tRU5EIF
执行加密后，也有一个值
[root@VM-0-2-centos scripts]# base64 /root/fisco2/nodes/127.0.0.1/node0/conf/node.key | tr -d "\n"
NDc1ZDY4NmNiZjFhODI2YTM1NjY2MjI4YjNmYzE2MGI=[root@VM-0-2-centos scripts]#

**Comment by HaoXuan40404** [comment]
使用curl -X POST --data '{"jsonrpc":"2.0","method":"encWithCipherKey","params":["'$fileStream'", "'$CIPHER_KEY'"],"id":83}' $URL |jq 调试一下请求key manager的返回，看下这里的返回值是什么fileStream是刚才base64你提交的值，CIPHER_KEY是你节点配置中的cipher_data_key=04bf9dbf1dada2987db53a5aed7c5ea1

**Comment by HaoXuan40404** [comment]
@JimmyShi22

**Comment by wanxi112233** [comment]
[root@VM-0-2-centos scripts]# curl -X POST --data '{"jsonrpc":"2.0","method":"encWithCipherKey","params":["NDc1ZDY4NmNiZjFhODI2YTM1NjY2MjI4YjNmYzE2MGI=", "04bf9dbf1dada2987db53a5aed7c5ea1"],"id":83}' 127.0.0.1:8150 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   320  100   173  100   147   284k   242k --:--:-- --:--:-- --:--:--  168k
{
  "id": 83,
  "jsonrpc": "2.0",
  "result": {
    "dataKey": "944dc2f0026c4363dff03ef320a171402889500f50b089adea1bc677cc0756f6664bff87d0727241a9adff40e88abdef",
    "error": 0,
    "info": "success"
  }
}

**Comment by HaoXuan40404** [comment]
944dc2f0026c4363dff03ef320a171402889500f50b089adea1bc677cc0756f6664bff87d0727241a9adff40e88abdef 应该才是节点加密后node.key正确的结果，再重试一下这个脚本？观察一下为什么最终写入文件的内容不正确

**Comment by wanxi112233** [comment]
当我手动替换密钥之后，仍然启动不了节点报错
  Exceed waiting time. Please try again to start node0 
Usage of FISCO-BCOS:
  -h [ --help ]                       print help information
  -v [ --version ]                    version of FISCO-BCOS
  -c [ --config ] arg (=./config.ini) config file path, eg. config.ini

这些启动的完整信息
[root@VM-0-2-centos scripts]# bash -x encrypt_node_key.sh 127.0.0.1 8150 /root/fisco2/nodes/127.0.0.1/node0/conf/node.key 04bf9dbf1dada2987db53a5aed7c5ea1
+ set -e
+ '[' '!' -n 04bf9dbf1dada2987db53a5aed7c5ea1 ']'
+ URL=127.0.0.1:8150
+ ORIGIN_FILE=/root/fisco2/nodes/127.0.0.1/node0/conf/node.key
+ CIPHER_KEY=04bf9dbf1dada2987db53a5aed7c5ea1
++ date +%s
+ BACKUP_FILE=/root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128
+ check_file /root/fisco2/nodes/127.0.0.1/node0/conf/node.key
+ file=/root/fisco2/nodes/127.0.0.1/node0/conf/node.key
+ '[' '!' -f /root/fisco2/nodes/127.0.0.1/node0/conf/node.key ']'
++ grep 'BEGIN PRIVATE KEY' /root/fisco2/nodes/127.0.0.1/node0/conf/node.key
+ '[' -z '-----BEGIN PRIVATE KEY-----' ']'
+ LOG_INFO 'Check file Ok.'
+ local 'content=Check file Ok.'
+ echo -e '\033[32m[INFO] Check file Ok.\033[0m'
[INFO] Check file Ok.
++ uname
+ OS_TYPE=Linux
+ [[ Linux == \L\i\n\u\x ]]
++ base64 /root/fisco2/nodes/127.0.0.1/node0/conf/node.key
++ tr -d '\n'
+ ffileStream=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0VBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFLQkcwd2F3SUJBUVFnWk1wblZIUTJydDRuKzFVRlBLY0IKai9sSW4vREpjTkgraktQaGl6eWNRcm1oUkFOQ0FBUVQ1ZERzVVFhVHRkaG1la2Q3MEJXVjRXcHJsK0R3cnJxQwo0S1l3c1Z0VkZjbFh0SHZrV3M3WWdKY0MyZVdjQ3ZYNzg3ZWZURnM2Qzkzbm5SWkl6UitECi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
+ curl -X POST --data '{"jsonrpc":"2.0","method":"encWithCipherKey","params":["", "04bf9dbf1dada2987db53a5aed7c5ea1"],"id":83}' 127.0.0.1:8150
+ jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   212  100   109  100   103   167k   158k --:--:-- --:--:-- --:--:--  106k
{
  "id": 83,
  "jsonrpc": "2.0",
  "result": {
    "dataKey": "475d686cbf1a826a35666228b3fc160b",
    "error": 0,
    "info": "success"
  }
}
++ curl -X POST --data '{"jsonrpc":"2.0","method":"encWithCipherKey","params":["", "04bf9dbf1dada2987db53a5aed7c5ea1"],"id":83}' 127.0.0.1:8150
++ jq .result.dataKey
++ sed 's/\"//g'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   212  100   109  100   103   214k   202k --:--:-- --:--:-- --:--:--  106k
+ cypherDataKey=475d686cbf1a826a35666228b3fc160b
+ '[' -z 475d686cbf1a826a35666228b3fc160b ']'
+ cp /root/fisco2/nodes/127.0.0.1/node0/conf/node.key /root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128
+ echo -e '475d686cbf1a826a35666228b3fc160b\c'
+ LOG_INFO 'File backup to "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128"'
+ local 'content=File backup to "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128"'
+ echo -e '\033[32m[INFO] File backup to "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128"\033[0m'
[INFO] File backup to "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key.bak.1732520128"
+ LOG_INFO '"/root/fisco2/nodes/127.0.0.1/node0/conf/node.key" encrypted!'
+ local 'content="/root/fisco2/nodes/127.0.0.1/node0/conf/node.key" encrypted!'
+ echo -e '\033[32m[INFO] "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key" encrypted!\033[0m'
[INFO] "/root/fisco2/nodes/127.0.0.1/node0/conf/node.key" encrypted!
我看到在传值的这里的时候
curl -X POST --data '{"jsonrpc":"2.0","method":"encWithCipherKey","params":["", "04bf9dbf1dada2987db53a5aed7c5ea1"],"id":83}' 127.0.0.1:8150 在这里好像给了一个空值，并不是上面获取到加密后的值

**Comment by HaoXuan40404** [comment]
你使用的是最新版本的keymanager吗

**Comment by wanxi112233** [comment]
对的，是最新版本的

**Comment by HaoXuan40404** [comment]
我在本地无法复现这个问题，你尝试注释掉脚本中#echo $fileStream，观察下这个变量是否被正确赋值

**Comment by HaoXuan40404** [comment]
fix with https://github.com/FISCO-BCOS/key-manager/commit/2592be403af3ccb3805213d3582f40b943ee67ea
